#!/bin/bash

case "$1" in
  Fitzroy)
    profile="profile=%7B%22status_text%22:%22Fitzroy%22,%22status_emoji%22:%22:briefcase:%22%7D"
    ;;
  *)
    profile="profile=%7B%22status_text%22:%22%22,%22status_emoji%22:%22%22%7D"
    ;;
esac

# replace slack_token with your token from
# https://api.slack.com/custom-integrations/legacy-tokens  
# Note that the Slack team don't like these tokens 'cos people do crazy things
# like post them to Github. Don't be one of those people.
curl -s -S --data "" "https://slack.com/api/users.profile.set?token=slack_token&$profile" | grep '"ok":true'
