#!/bin/sh

git init

cat <<EOF > .gitignore
.DS_Store
log/*.log
tmp/**/*
db/*.sqlite3
coverage
doc/app/*
EOF

find . -type d -empty -exec touch {}/.gitignore \;

rm -rf test
script/generate rspec

rm public/public/index.html

git add .
git commit -a -m "Initial import."