#!/bin/bash
host=git.trike.com.au

function usage () {
   cat <<EOF
Usage: $progname [-h hostname] [-u username] [-p] [project=pwd]

OPTIONS
     -p   projectfiles mode (project will be pushed to ~git/projectfiles/project instead of ~git/project)
EOF
   exit 0
}

pushpath=

while getopts "ph:" opt; do
  case $opt in
    h ) host=$OPTARG ;;
    p ) pushpath=projectfiles/;;
    \?) usage;;
  esac
done
shift $(($OPTIND - 1))

if [ -z $1 ]; then
  project=`basename \`pwd\``
else
  project=$1
fi

ssh $host "cd ~git/$pushpath && umask 2 && mkdir $project.git && cd $project.git && git --bare init" && \
git remote add origin git@$host:$pushpath$project.git && \
git push origin master && \
echo && \
echo "Project pushed to:" && \
git remote show origin
