#!/bin/bash
MD5=`which md5sum`
if [ ! -x "$MD5" ]
then
    MD5=`which md5` # OSX
fi
if [ ! -x "$MD5" ]
then
    echo "Utility md5sum (or md5) not found." >&2
    exit 1
fi

#XCLIP=`which xclip`
XCLIP=`which pbcopy`
if [ ! -x "$XCLIP" ]
then
    echo "Utility xclip not found." >&2
    exit 1
fi

if [ $# -ne 1 ]
then
    echo -n "Enter the domain> "
    read DOMAIN
else
    DOMAIN=$1
fi

echo -n "Enter your master password> "
stty -echo
echo -n "$(head -1 | cat - <(echo :$DOMAIN) - | tr -d \\n | $MD5 | cut -b 1-8)" | $XCLIP
stty echo
echo -e "\nPassword has been copied to clipboard"
