#!/usr/bin/env ruby -w

require File.join(File.dirname(__FILE__), "../lib/notify")

directory = File.dirname(__FILE__)
`#{File.join(directory, "finder-path")}`
path = IO.popen('pbpaste', 'r').read
path_xdropbox = path.sub(/^.*Dropbox/, 'Dropbox:')
IO.popen('pbcopy', 'w').print(path_xdropbox)
notify(path_xdropbox)
