#!/usr/bin/env ruby
# HTML unescape the contents of the OSX clipboard
%w[rubygems escape htmlentities].each {|l| require l }
`/opt/local/bin/echo -n #{Escape.shell_single_word(HTMLEntities.decode_entities(`pbpaste`))} | pbcopy`
