#!/bin/bash
MD5=`which md5sum`
if [ ! -x "$MD5" ]
then
  MD5=`which md5` # OSX
fi
if [ ! -x "$MD5" ]
then
  echo "Utility md5sum (or md5) not found." >&2
  exit 1
fi

XCLIP=`which pbcopy`
if [ ! -x "$XCLIP" ]
then
  echo "Utility xclip not found." >&2
  exit 1
fi

if [ $# -ne 1 ]
then
  DOMAIN="$(/usr/bin/osascript 2>/dev/null <<-'__HEREDOC__'
with timeout of 300 seconds
  tell application "System Events"
    activate
    set input to display dialog "Please enter the domain:" with title "Domain" with icon note default answer "" buttons {"Cancel", "OK"} default button 2 giving up after 295
    return text returned of input as string
  end tell
end timeout
  __HEREDOC__
  )"
else
  DOMAIN=$1
fi

echo -n "$(/usr/bin/osascript 2>/dev/null <<-'__HEREDOC__'
with timeout of 300 seconds
tell application "System Events"
  activate
  set input to display dialog "Please enter your master password:" with title "Password" with icon caution default answer "" buttons {"Cancel", "OK"} default button 2 giving up after 295 with hidden answer
  return text returned of input as string
end tell
end timeout
__HEREDOC__
)" | cat - <(echo :$DOMAIN) - | tr -d \\n | $MD5 | cut -b 1-8 | tr -d \\n | $XCLIP

echo -e "\nPassword has been copied to clipboard"
