#!/usr/bin/env ruby
# Downcase the contents of the OSX clipboard

def notify(message)
  require 'shellwords'
  `/usr/local/bin/growlnotify -a Quicksilver -m #{message.shellescape}`
  message
end

output = IO.popen('pbpaste', 'r').read.downcase
IO.popen('pbcopy', 'w').print(output)
notify(output)
