#!/usr/bin/env ruby
# HTML decode the contents of the OSX clipboard
# WARNING: this pretty much doesn't work - I guess that pbcopy isn't cooperating

%w[rubygems htmlentities].each {|l| require l }

require File.join(File.dirname(__FILE__), "../lib/notify")

output = HTMLEntities.encode_entities(IO.popen('pbpaste', 'r').read)
IO.popen('pbcopy', 'w').print(output)
notify(output)
