#!/usr/bin/env ruby
# Sentence caserize the contents of the OSX clipboard
%w[rubygems active_support].each {|l| require l }

require File.join(File.dirname(__FILE__), "../lib/notify")

output = IO.popen('pbpaste', 'r').read.humanize
IO.popen('pbcopy', 'w').print(output)
notify(output)
