#!/usr/bin/env ruby
# Sentence caserize the contents of the OSX clipboard

require File.join(File.dirname(__FILE__), "../lib/notify")

output = IO.popen('pbpaste', 'r').read.downcase.sub(/^./) {|x| x.upcase }
IO.popen('pbcopy', 'w').print(output)
notify(output)
