#!/usr/bin/env ruby

# Convert the contents of the clipboard to html (with
# RedCloth[http://whytheluckystiff.net/ruby/redcloth/], so assuming it's
# Textile or Markdown) and send it to STDOUT

%w[rubygems redcloth].each {|l| require l }

def notify(message)
  require 'shellwords'
  `/usr/local/bin/growlnotify -a Quicksilver -m #{message.shellescape}`
  message
end

clipboard = IO.popen('pbpaste', 'r').read
output = RedCloth.new(clipboard).to_html
output.gsub!(%r|^(?:<p>)?(.*?)(?:</p>)?$|,'\1')  # remove wrapping paragraph

IO.popen('pbcopy', 'w').print(output)
notify(output)
