#!/usr/bin/env ruby

# Convert the contents of the clipboard to html (with
# RedCloth[http://whytheluckystiff.net/ruby/redcloth/], so assuming it's
# Textile or Markdown) and send it to STDOUT

%w[rubygems redcloth].each {|l| require l }

require File.join(File.dirname(__FILE__), "../lib/notify")

clipboard = IO.popen('pbpaste', 'r').read
output = RedCloth.new(clipboard).to_html
output.gsub!(%r|^(?:<p>)?(.*?)(?:</p>)?$|,'\1')  # remove wrapping paragraph

IO.popen('pbcopy', 'w').print(output)
notify(output)
