#!/usr/bin/env ruby
# Title caserize the contents of the OSX clipboard

require File.join(File.dirname(__FILE__), "../lib/notify")

pb = IO.popen('pbpaste', 'r').read
output = ""
pb.each("\s") {|w| output << w.capitalize}
IO.popen('pbcopy', 'w').print(output)
notify(output)
