#!/usr/bin/env ruby
# Title caserize the contents of the OSX clipboard

def notify(message)
  require 'shellwords'
  `/usr/local/bin/growlnotify -a Quicksilver -m #{message.shellescape}`
  message
end

pb = IO.popen('pbpaste', 'r').read
output = ""
pb.each("\s") {|w| output << w.capitalize}
IO.popen('pbcopy', 'w').print(output)
notify(output)
