#!/usr/bin/env ruby
# Quoted-printable unescape the contents of the OSX clipboard

require File.join(File.dirname(__FILE__), "../lib/notify")

class String
  def to_quoted_printable(*args)
    [self].pack("M").gsub(/\n/, "\r\n")
  end
  def from_quoted_printable
    self.gsub(/\r\n/, "\n").unpack("M").first
  end
end

output = IO.popen('pbpaste', 'r').read.from_quoted_printable
IO.popen('pbcopy', 'w').print(output)
notify(output)
