#!/usr/bin/env ruby
# CGI unescape the contents of the OSX clipboard

require 'cgi'

require File.join(File.dirname(__FILE__), "../lib/notify")

output = CGI.unescape(IO.popen('pbpaste', 'r').read)
IO.popen('pbcopy', 'w').print(output)
notify(output)
