#!/usr/bin/env ruby
# Undasherize the clipboard on OSX (to spaces)

def notify(message)
  require 'shellwords'
  `/usr/local/bin/growlnotify -a Quicksilver -m #{message.shellescape}`
  message
end

output = IO.popen('pbpaste', 'r').read.gsub(/[-_]+/," ")
IO.popen('pbcopy', 'w').print(output)
notify(output)
