#!/usr/bin/env ruby
# HTML decode the contents of the OSX clipboard
# WARNING: this pretty much doesn't work - I guess that pbcopy isn't cooperating

%w[rubygems htmlentities].each {|l| require l }
IO.popen('pbcopy', 'w').print(HTMLEntities.decode_entities(IO.popen('pbpaste', 'r').read))
