#!/usr/bin/env ruby
# CGI unescape the contents of the OSX clipboard

require 'cgi'

def notify(message)
  require 'shellwords'
  `/usr/local/bin/growlnotify -a Quicksilver -m #{message.shellescape}`
  message
end

output = CGI.unescape(IO.popen('pbpaste', 'r').read)
IO.popen('pbcopy', 'w').print(output)
notify(output)
