require 'rubygems'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = Dir.glob('*')
end

desc "Run spec task, but only emit to STDOUT on failure"
task :cron do
  puts "TODO"
  exit 1
end

task :default => :spec
