#!/bin/bash

# Clear Chrome File System if it's too large
GRRDIR="Library/Application Support/Google/Chrome/Default/File System"
GRRLIMIT=3  # GB
SIZE=$(du -sm ~/"$GRRDIR" 2>/dev/null | cut -f1)

LOG=/var/log/grr.dirs.log

if [ $SIZE -gt ${GRRLIMIT}000 ]; then
  rm -rf ~/"$GRRDIR"/*
  echo "$(date) | $GRRDIR was > ${GRRLIMIT}GB, cleared" | tee -a $LOG | ~/bin/notify
else
  echo "$(date) | $GRRDIR was $SIZE Mb" >> $LOG
fi
