#!/bin/bash

# Clear Dropbox cache if it's too large
GRRDIR="Dropbox (Bellroy)/.dropbox.cache"
GRRLIMIT=5  # GB

SIZE=$(du -sm ~/"$GRRDIR" 2>/dev/null | cut -f1)
LOG=/tmp/grr.dirs.log

if [ $SIZE -gt ${GRRLIMIT}000 ]; then
  rm -rf ~/"$GRRDIR"/*
  echo "$(date) | $GRRDIR was > ${GRRLIMIT}GB, cleared" | tee -a $LOG | ~/bin/notify
else
  echo "$(date) | $GRRDIR was $SIZE Mb" >> $LOG
fi
