#!/bin/sh

{ source "${BASH_SOURCE%/*}/Wemo/wemoOfficeOff" && /usr/bin/osascript -e "tell application \"Finder\" to eject (every disk whose ejectable is true)" && /usr/bin/pmset sleepnow; } >/tmp/leaveoffice.log 2>&1
