#!/bin/bash

{
  for v in $(diskutil corestorage list | grep Logical\ Volume | grep -v "Family" | grep -v Group | grep -v 470C-A323-D4F7F31BDD60 | cut -c 5- | awk '{ print $4 }'); do
    if diskutil corestorage list "$v" | grep -q "Status.*Locked"; then
      echo; date "+%Y-%m-%dT%H:%M:%S%z"
      security find-generic-password -wa Files | diskutil coreStorage unlockLV "$v" -stdinpassphrase
    fi
    if diskutil info "$v" | grep -q "Mounted.*No"; then
      echo; date "+%Y-%m-%dT%H:%M:%S%z"
      diskutil mount "$v"
    fi
  done
} >>/tmp/mountdrives.log 2>&1
