%w[rubygems rake].each {|l| require l }
 
task :default => :install_actions

desc "Install Applescript actions to ~/Library/Application\ Support/Quicksilver/Actions/"
task :install_actions

Dir["*.scpt"].each do |action|
  actiondir = File.expand_path("~/Library/Application\ Support/Quicksilver/Actions/")
  actionfile = File.join(actiondir, action)
  file actionfile => action do
    mkdir_p actiondir
    cp action, actiondir
  end
  task install_actions: actionfile

  desc "file #{actionfile} => #{action}"
  task File.basename(action, ".*") => actionfile
end

